/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const AchDepositSchedulesListAchDepositSchedulesRequest$inboundSchema = z.object({
    account_id: z.string(),
    filter: z.string().optional(),
    page_size: z.number().int().optional(),
    page_token: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "page_size": "pageSize",
        "page_token": "pageToken",
    });
});
/** @internal */
export const AchDepositSchedulesListAchDepositSchedulesRequest$outboundSchema = z.object({
    accountId: z.string(),
    filter: z.string().optional(),
    pageSize: z.number().int().optional(),
    pageToken: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        pageSize: "page_size",
        pageToken: "page_token",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var AchDepositSchedulesListAchDepositSchedulesRequest$;
(function (AchDepositSchedulesListAchDepositSchedulesRequest$) {
    /** @deprecated use `AchDepositSchedulesListAchDepositSchedulesRequest$inboundSchema` instead. */
    AchDepositSchedulesListAchDepositSchedulesRequest$.inboundSchema = AchDepositSchedulesListAchDepositSchedulesRequest$inboundSchema;
    /** @deprecated use `AchDepositSchedulesListAchDepositSchedulesRequest$outboundSchema` instead. */
    AchDepositSchedulesListAchDepositSchedulesRequest$.outboundSchema = AchDepositSchedulesListAchDepositSchedulesRequest$outboundSchema;
})(AchDepositSchedulesListAchDepositSchedulesRequest$ || (AchDepositSchedulesListAchDepositSchedulesRequest$ = {}));
export function achDepositSchedulesListAchDepositSchedulesRequestToJSON(achDepositSchedulesListAchDepositSchedulesRequest) {
    return JSON.stringify(AchDepositSchedulesListAchDepositSchedulesRequest$outboundSchema.parse(achDepositSchedulesListAchDepositSchedulesRequest));
}
export function achDepositSchedulesListAchDepositSchedulesRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => AchDepositSchedulesListAchDepositSchedulesRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AchDepositSchedulesListAchDepositSchedulesRequest' from JSON`);
}
/** @internal */
export const AchDepositSchedulesListAchDepositSchedulesResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListAchDepositSchedulesResponse: components
        .ListAchDepositSchedulesResponse$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "ListAchDepositSchedulesResponse": "listAchDepositSchedulesResponse",
        "Status": "status",
    });
});
/** @internal */
export const AchDepositSchedulesListAchDepositSchedulesResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    listAchDepositSchedulesResponse: components
        .ListAchDepositSchedulesResponse$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        listAchDepositSchedulesResponse: "ListAchDepositSchedulesResponse",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var AchDepositSchedulesListAchDepositSchedulesResponse$;
(function (AchDepositSchedulesListAchDepositSchedulesResponse$) {
    /** @deprecated use `AchDepositSchedulesListAchDepositSchedulesResponse$inboundSchema` instead. */
    AchDepositSchedulesListAchDepositSchedulesResponse$.inboundSchema = AchDepositSchedulesListAchDepositSchedulesResponse$inboundSchema;
    /** @deprecated use `AchDepositSchedulesListAchDepositSchedulesResponse$outboundSchema` instead. */
    AchDepositSchedulesListAchDepositSchedulesResponse$.outboundSchema = AchDepositSchedulesListAchDepositSchedulesResponse$outboundSchema;
})(AchDepositSchedulesListAchDepositSchedulesResponse$ || (AchDepositSchedulesListAchDepositSchedulesResponse$ = {}));
export function achDepositSchedulesListAchDepositSchedulesResponseToJSON(achDepositSchedulesListAchDepositSchedulesResponse) {
    return JSON.stringify(AchDepositSchedulesListAchDepositSchedulesResponse$outboundSchema.parse(achDepositSchedulesListAchDepositSchedulesResponse));
}
export function achDepositSchedulesListAchDepositSchedulesResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => AchDepositSchedulesListAchDepositSchedulesResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AchDepositSchedulesListAchDepositSchedulesResponse' from JSON`);
}
//# sourceMappingURL=achdepositscheduleslistachdepositschedules.js.map