/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const IctWithdrawalsGetIctWithdrawalRequest$inboundSchema = z.object({
    account_id: z.string(),
    ictWithdrawal_id: z.string(),
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "ictWithdrawal_id": "ictWithdrawalId",
    });
});
/** @internal */
export const IctWithdrawalsGetIctWithdrawalRequest$outboundSchema = z.object({
    accountId: z.string(),
    ictWithdrawalId: z.string(),
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        ictWithdrawalId: "ictWithdrawal_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IctWithdrawalsGetIctWithdrawalRequest$;
(function (IctWithdrawalsGetIctWithdrawalRequest$) {
    /** @deprecated use `IctWithdrawalsGetIctWithdrawalRequest$inboundSchema` instead. */
    IctWithdrawalsGetIctWithdrawalRequest$.inboundSchema = IctWithdrawalsGetIctWithdrawalRequest$inboundSchema;
    /** @deprecated use `IctWithdrawalsGetIctWithdrawalRequest$outboundSchema` instead. */
    IctWithdrawalsGetIctWithdrawalRequest$.outboundSchema = IctWithdrawalsGetIctWithdrawalRequest$outboundSchema;
})(IctWithdrawalsGetIctWithdrawalRequest$ || (IctWithdrawalsGetIctWithdrawalRequest$ = {}));
export function ictWithdrawalsGetIctWithdrawalRequestToJSON(ictWithdrawalsGetIctWithdrawalRequest) {
    return JSON.stringify(IctWithdrawalsGetIctWithdrawalRequest$outboundSchema.parse(ictWithdrawalsGetIctWithdrawalRequest));
}
export function ictWithdrawalsGetIctWithdrawalRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => IctWithdrawalsGetIctWithdrawalRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'IctWithdrawalsGetIctWithdrawalRequest' from JSON`);
}
/** @internal */
export const IctWithdrawalsGetIctWithdrawalResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    IctWithdrawal: components.IctWithdrawal$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "IctWithdrawal": "ictWithdrawal",
        "Status": "status",
    });
});
/** @internal */
export const IctWithdrawalsGetIctWithdrawalResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    ictWithdrawal: components.IctWithdrawal$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        ictWithdrawal: "IctWithdrawal",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IctWithdrawalsGetIctWithdrawalResponse$;
(function (IctWithdrawalsGetIctWithdrawalResponse$) {
    /** @deprecated use `IctWithdrawalsGetIctWithdrawalResponse$inboundSchema` instead. */
    IctWithdrawalsGetIctWithdrawalResponse$.inboundSchema = IctWithdrawalsGetIctWithdrawalResponse$inboundSchema;
    /** @deprecated use `IctWithdrawalsGetIctWithdrawalResponse$outboundSchema` instead. */
    IctWithdrawalsGetIctWithdrawalResponse$.outboundSchema = IctWithdrawalsGetIctWithdrawalResponse$outboundSchema;
})(IctWithdrawalsGetIctWithdrawalResponse$ || (IctWithdrawalsGetIctWithdrawalResponse$ = {}));
export function ictWithdrawalsGetIctWithdrawalResponseToJSON(ictWithdrawalsGetIctWithdrawalResponse) {
    return JSON.stringify(IctWithdrawalsGetIctWithdrawalResponse$outboundSchema.parse(ictWithdrawalsGetIctWithdrawalResponse));
}
export function ictWithdrawalsGetIctWithdrawalResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => IctWithdrawalsGetIctWithdrawalResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'IctWithdrawalsGetIctWithdrawalResponse' from JSON`);
}
//# sourceMappingURL=ictwithdrawalsgetictwithdrawal.js.map