/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const IctWithdrawalsForceApproveIctWithdrawalRequest$inboundSchema = z.object({
    account_id: z.string(),
    ictWithdrawal_id: z.string(),
    ForceApproveIctWithdrawalRequestCreate: components.ForceApproveIctWithdrawalRequestCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "ictWithdrawal_id": "ictWithdrawalId",
        "ForceApproveIctWithdrawalRequestCreate": "forceApproveIctWithdrawalRequestCreate",
    });
});
/** @internal */
export const IctWithdrawalsForceApproveIctWithdrawalRequest$outboundSchema = z.object({
    accountId: z.string(),
    ictWithdrawalId: z.string(),
    forceApproveIctWithdrawalRequestCreate: components.ForceApproveIctWithdrawalRequestCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        ictWithdrawalId: "ictWithdrawal_id",
        forceApproveIctWithdrawalRequestCreate: "ForceApproveIctWithdrawalRequestCreate",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IctWithdrawalsForceApproveIctWithdrawalRequest$;
(function (IctWithdrawalsForceApproveIctWithdrawalRequest$) {
    /** @deprecated use `IctWithdrawalsForceApproveIctWithdrawalRequest$inboundSchema` instead. */
    IctWithdrawalsForceApproveIctWithdrawalRequest$.inboundSchema = IctWithdrawalsForceApproveIctWithdrawalRequest$inboundSchema;
    /** @deprecated use `IctWithdrawalsForceApproveIctWithdrawalRequest$outboundSchema` instead. */
    IctWithdrawalsForceApproveIctWithdrawalRequest$.outboundSchema = IctWithdrawalsForceApproveIctWithdrawalRequest$outboundSchema;
})(IctWithdrawalsForceApproveIctWithdrawalRequest$ || (IctWithdrawalsForceApproveIctWithdrawalRequest$ = {}));
export function ictWithdrawalsForceApproveIctWithdrawalRequestToJSON(ictWithdrawalsForceApproveIctWithdrawalRequest) {
    return JSON.stringify(IctWithdrawalsForceApproveIctWithdrawalRequest$outboundSchema.parse(ictWithdrawalsForceApproveIctWithdrawalRequest));
}
export function ictWithdrawalsForceApproveIctWithdrawalRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => IctWithdrawalsForceApproveIctWithdrawalRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'IctWithdrawalsForceApproveIctWithdrawalRequest' from JSON`);
}
/** @internal */
export const IctWithdrawalsForceApproveIctWithdrawalResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    IctWithdrawal: components.IctWithdrawal$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "IctWithdrawal": "ictWithdrawal",
        "Status": "status",
    });
});
/** @internal */
export const IctWithdrawalsForceApproveIctWithdrawalResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    ictWithdrawal: components.IctWithdrawal$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        ictWithdrawal: "IctWithdrawal",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IctWithdrawalsForceApproveIctWithdrawalResponse$;
(function (IctWithdrawalsForceApproveIctWithdrawalResponse$) {
    /** @deprecated use `IctWithdrawalsForceApproveIctWithdrawalResponse$inboundSchema` instead. */
    IctWithdrawalsForceApproveIctWithdrawalResponse$.inboundSchema = IctWithdrawalsForceApproveIctWithdrawalResponse$inboundSchema;
    /** @deprecated use `IctWithdrawalsForceApproveIctWithdrawalResponse$outboundSchema` instead. */
    IctWithdrawalsForceApproveIctWithdrawalResponse$.outboundSchema = IctWithdrawalsForceApproveIctWithdrawalResponse$outboundSchema;
})(IctWithdrawalsForceApproveIctWithdrawalResponse$ || (IctWithdrawalsForceApproveIctWithdrawalResponse$ = {}));
export function ictWithdrawalsForceApproveIctWithdrawalResponseToJSON(ictWithdrawalsForceApproveIctWithdrawalResponse) {
    return JSON.stringify(IctWithdrawalsForceApproveIctWithdrawalResponse$outboundSchema.parse(ictWithdrawalsForceApproveIctWithdrawalResponse));
}
export function ictWithdrawalsForceApproveIctWithdrawalResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => IctWithdrawalsForceApproveIctWithdrawalResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'IctWithdrawalsForceApproveIctWithdrawalResponse' from JSON`);
}
//# sourceMappingURL=ictwithdrawalsforceapproveictwithdrawal.js.map