/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const RetirementConstraintsRetrieveContributionConstraintsRequest$inboundSchema = z.object({
    account_id: z.string(),
    RetrieveContributionConstraintsRequestCreate: components.RetrieveContributionConstraintsRequestCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "RetrieveContributionConstraintsRequestCreate": "retrieveContributionConstraintsRequestCreate",
    });
});
/** @internal */
export const RetirementConstraintsRetrieveContributionConstraintsRequest$outboundSchema = z.object({
    accountId: z.string(),
    retrieveContributionConstraintsRequestCreate: components.RetrieveContributionConstraintsRequestCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        retrieveContributionConstraintsRequestCreate: "RetrieveContributionConstraintsRequestCreate",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsRetrieveContributionConstraintsRequest$;
(function (RetirementConstraintsRetrieveContributionConstraintsRequest$) {
    /** @deprecated use `RetirementConstraintsRetrieveContributionConstraintsRequest$inboundSchema` instead. */
    RetirementConstraintsRetrieveContributionConstraintsRequest$.inboundSchema = RetirementConstraintsRetrieveContributionConstraintsRequest$inboundSchema;
    /** @deprecated use `RetirementConstraintsRetrieveContributionConstraintsRequest$outboundSchema` instead. */
    RetirementConstraintsRetrieveContributionConstraintsRequest$.outboundSchema = RetirementConstraintsRetrieveContributionConstraintsRequest$outboundSchema;
})(RetirementConstraintsRetrieveContributionConstraintsRequest$ || (RetirementConstraintsRetrieveContributionConstraintsRequest$ = {}));
export function retirementConstraintsRetrieveContributionConstraintsRequestToJSON(retirementConstraintsRetrieveContributionConstraintsRequest) {
    return JSON.stringify(RetirementConstraintsRetrieveContributionConstraintsRequest$outboundSchema
        .parse(retirementConstraintsRetrieveContributionConstraintsRequest));
}
export function retirementConstraintsRetrieveContributionConstraintsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsRetrieveContributionConstraintsRequest$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsRetrieveContributionConstraintsRequest' from JSON`);
}
/** @internal */
export const RetirementConstraintsRetrieveContributionConstraintsResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ContributionConstraints: components.ContributionConstraints$inboundSchema
        .optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "ContributionConstraints": "contributionConstraints",
        "Status": "status",
    });
});
/** @internal */
export const RetirementConstraintsRetrieveContributionConstraintsResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    contributionConstraints: components.ContributionConstraints$outboundSchema
        .optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        contributionConstraints: "ContributionConstraints",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsRetrieveContributionConstraintsResponse$;
(function (RetirementConstraintsRetrieveContributionConstraintsResponse$) {
    /** @deprecated use `RetirementConstraintsRetrieveContributionConstraintsResponse$inboundSchema` instead. */
    RetirementConstraintsRetrieveContributionConstraintsResponse$.inboundSchema = RetirementConstraintsRetrieveContributionConstraintsResponse$inboundSchema;
    /** @deprecated use `RetirementConstraintsRetrieveContributionConstraintsResponse$outboundSchema` instead. */
    RetirementConstraintsRetrieveContributionConstraintsResponse$.outboundSchema = RetirementConstraintsRetrieveContributionConstraintsResponse$outboundSchema;
})(RetirementConstraintsRetrieveContributionConstraintsResponse$ || (RetirementConstraintsRetrieveContributionConstraintsResponse$ = {}));
export function retirementConstraintsRetrieveContributionConstraintsResponseToJSON(retirementConstraintsRetrieveContributionConstraintsResponse) {
    return JSON.stringify(RetirementConstraintsRetrieveContributionConstraintsResponse$outboundSchema
        .parse(retirementConstraintsRetrieveContributionConstraintsResponse));
}
export function retirementConstraintsRetrieveContributionConstraintsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsRetrieveContributionConstraintsResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsRetrieveContributionConstraintsResponse' from JSON`);
}
//# sourceMappingURL=retirementconstraintsretrievecontributionconstraints.js.map