/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const RetirementConstraintsRetrieveDistributionConstraintsRequest$inboundSchema = z.object({
    account_id: z.string(),
    RetrieveDistributionConstraintsRequestCreate: components.RetrieveDistributionConstraintsRequestCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "RetrieveDistributionConstraintsRequestCreate": "retrieveDistributionConstraintsRequestCreate",
    });
});
/** @internal */
export const RetirementConstraintsRetrieveDistributionConstraintsRequest$outboundSchema = z.object({
    accountId: z.string(),
    retrieveDistributionConstraintsRequestCreate: components.RetrieveDistributionConstraintsRequestCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        retrieveDistributionConstraintsRequestCreate: "RetrieveDistributionConstraintsRequestCreate",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsRetrieveDistributionConstraintsRequest$;
(function (RetirementConstraintsRetrieveDistributionConstraintsRequest$) {
    /** @deprecated use `RetirementConstraintsRetrieveDistributionConstraintsRequest$inboundSchema` instead. */
    RetirementConstraintsRetrieveDistributionConstraintsRequest$.inboundSchema = RetirementConstraintsRetrieveDistributionConstraintsRequest$inboundSchema;
    /** @deprecated use `RetirementConstraintsRetrieveDistributionConstraintsRequest$outboundSchema` instead. */
    RetirementConstraintsRetrieveDistributionConstraintsRequest$.outboundSchema = RetirementConstraintsRetrieveDistributionConstraintsRequest$outboundSchema;
})(RetirementConstraintsRetrieveDistributionConstraintsRequest$ || (RetirementConstraintsRetrieveDistributionConstraintsRequest$ = {}));
export function retirementConstraintsRetrieveDistributionConstraintsRequestToJSON(retirementConstraintsRetrieveDistributionConstraintsRequest) {
    return JSON.stringify(RetirementConstraintsRetrieveDistributionConstraintsRequest$outboundSchema
        .parse(retirementConstraintsRetrieveDistributionConstraintsRequest));
}
export function retirementConstraintsRetrieveDistributionConstraintsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsRetrieveDistributionConstraintsRequest$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsRetrieveDistributionConstraintsRequest' from JSON`);
}
/** @internal */
export const RetirementConstraintsRetrieveDistributionConstraintsResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    DistributionConstraints: components.DistributionConstraints$inboundSchema
        .optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "DistributionConstraints": "distributionConstraints",
        "Status": "status",
    });
});
/** @internal */
export const RetirementConstraintsRetrieveDistributionConstraintsResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    distributionConstraints: components.DistributionConstraints$outboundSchema
        .optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        distributionConstraints: "DistributionConstraints",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsRetrieveDistributionConstraintsResponse$;
(function (RetirementConstraintsRetrieveDistributionConstraintsResponse$) {
    /** @deprecated use `RetirementConstraintsRetrieveDistributionConstraintsResponse$inboundSchema` instead. */
    RetirementConstraintsRetrieveDistributionConstraintsResponse$.inboundSchema = RetirementConstraintsRetrieveDistributionConstraintsResponse$inboundSchema;
    /** @deprecated use `RetirementConstraintsRetrieveDistributionConstraintsResponse$outboundSchema` instead. */
    RetirementConstraintsRetrieveDistributionConstraintsResponse$.outboundSchema = RetirementConstraintsRetrieveDistributionConstraintsResponse$outboundSchema;
})(RetirementConstraintsRetrieveDistributionConstraintsResponse$ || (RetirementConstraintsRetrieveDistributionConstraintsResponse$ = {}));
export function retirementConstraintsRetrieveDistributionConstraintsResponseToJSON(retirementConstraintsRetrieveDistributionConstraintsResponse) {
    return JSON.stringify(RetirementConstraintsRetrieveDistributionConstraintsResponse$outboundSchema
        .parse(retirementConstraintsRetrieveDistributionConstraintsResponse));
}
export function retirementConstraintsRetrieveDistributionConstraintsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsRetrieveDistributionConstraintsResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsRetrieveDistributionConstraintsResponse' from JSON`);
}
//# sourceMappingURL=retirementconstraintsretrievedistributionconstraints.js.map