/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as components from "../components/index.js";
/** @internal */
export const RetirementConstraintsListContributionSummariesRequest$inboundSchema = z.object({
    account_id: z.string(),
    page_size: z.number().int().optional(),
    page_token: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        "account_id": "accountId",
        "page_size": "pageSize",
        "page_token": "pageToken",
    });
});
/** @internal */
export const RetirementConstraintsListContributionSummariesRequest$outboundSchema = z.object({
    accountId: z.string(),
    pageSize: z.number().int().optional(),
    pageToken: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        accountId: "account_id",
        pageSize: "page_size",
        pageToken: "page_token",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsListContributionSummariesRequest$;
(function (RetirementConstraintsListContributionSummariesRequest$) {
    /** @deprecated use `RetirementConstraintsListContributionSummariesRequest$inboundSchema` instead. */
    RetirementConstraintsListContributionSummariesRequest$.inboundSchema = RetirementConstraintsListContributionSummariesRequest$inboundSchema;
    /** @deprecated use `RetirementConstraintsListContributionSummariesRequest$outboundSchema` instead. */
    RetirementConstraintsListContributionSummariesRequest$.outboundSchema = RetirementConstraintsListContributionSummariesRequest$outboundSchema;
})(RetirementConstraintsListContributionSummariesRequest$ || (RetirementConstraintsListContributionSummariesRequest$ = {}));
export function retirementConstraintsListContributionSummariesRequestToJSON(retirementConstraintsListContributionSummariesRequest) {
    return JSON.stringify(RetirementConstraintsListContributionSummariesRequest$outboundSchema.parse(retirementConstraintsListContributionSummariesRequest));
}
export function retirementConstraintsListContributionSummariesRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsListContributionSummariesRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsListContributionSummariesRequest' from JSON`);
}
/** @internal */
export const RetirementConstraintsListContributionSummariesResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListContributionSummariesResponse: components
        .ListContributionSummariesResponse$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "ListContributionSummariesResponse": "listContributionSummariesResponse",
        "Status": "status",
    });
});
/** @internal */
export const RetirementConstraintsListContributionSummariesResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    listContributionSummariesResponse: components
        .ListContributionSummariesResponse$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        httpMeta: "HttpMeta",
        listContributionSummariesResponse: "ListContributionSummariesResponse",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RetirementConstraintsListContributionSummariesResponse$;
(function (RetirementConstraintsListContributionSummariesResponse$) {
    /** @deprecated use `RetirementConstraintsListContributionSummariesResponse$inboundSchema` instead. */
    RetirementConstraintsListContributionSummariesResponse$.inboundSchema = RetirementConstraintsListContributionSummariesResponse$inboundSchema;
    /** @deprecated use `RetirementConstraintsListContributionSummariesResponse$outboundSchema` instead. */
    RetirementConstraintsListContributionSummariesResponse$.outboundSchema = RetirementConstraintsListContributionSummariesResponse$outboundSchema;
})(RetirementConstraintsListContributionSummariesResponse$ || (RetirementConstraintsListContributionSummariesResponse$ = {}));
export function retirementConstraintsListContributionSummariesResponseToJSON(retirementConstraintsListContributionSummariesResponse) {
    return JSON.stringify(RetirementConstraintsListContributionSummariesResponse$outboundSchema.parse(retirementConstraintsListContributionSummariesResponse));
}
export function retirementConstraintsListContributionSummariesResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RetirementConstraintsListContributionSummariesResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'RetirementConstraintsListContributionSummariesResponse' from JSON`);
}
//# sourceMappingURL=retirementconstraintslistcontributionsummaries.js.map