"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriberListPushSubscriptionDeliveriesResponse$ = exports.SubscriberListPushSubscriptionDeliveriesResponse$outboundSchema = exports.SubscriberListPushSubscriptionDeliveriesResponse$inboundSchema = exports.SubscriberListPushSubscriptionDeliveriesRequest$ = exports.SubscriberListPushSubscriptionDeliveriesRequest$outboundSchema = exports.SubscriberListPushSubscriptionDeliveriesRequest$inboundSchema = void 0;
exports.subscriberListPushSubscriptionDeliveriesRequestToJSON = subscriberListPushSubscriptionDeliveriesRequestToJSON;
exports.subscriberListPushSubscriptionDeliveriesRequestFromJSON = subscriberListPushSubscriptionDeliveriesRequestFromJSON;
exports.subscriberListPushSubscriptionDeliveriesResponseToJSON = subscriberListPushSubscriptionDeliveriesResponseToJSON;
exports.subscriberListPushSubscriptionDeliveriesResponseFromJSON = subscriberListPushSubscriptionDeliveriesResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.SubscriberListPushSubscriptionDeliveriesRequest$inboundSchema = z.object({
    subscription_id: z.string(),
    filter: z.string().optional(),
    page_size: z.number().int().optional(),
    page_token: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "subscription_id": "subscriptionId",
        "page_size": "pageSize",
        "page_token": "pageToken",
    });
});
/** @internal */
exports.SubscriberListPushSubscriptionDeliveriesRequest$outboundSchema = z.object({
    subscriptionId: z.string(),
    filter: z.string().optional(),
    pageSize: z.number().int().optional(),
    pageToken: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        subscriptionId: "subscription_id",
        pageSize: "page_size",
        pageToken: "page_token",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var SubscriberListPushSubscriptionDeliveriesRequest$;
(function (SubscriberListPushSubscriptionDeliveriesRequest$) {
    /** @deprecated use `SubscriberListPushSubscriptionDeliveriesRequest$inboundSchema` instead. */
    SubscriberListPushSubscriptionDeliveriesRequest$.inboundSchema = exports.SubscriberListPushSubscriptionDeliveriesRequest$inboundSchema;
    /** @deprecated use `SubscriberListPushSubscriptionDeliveriesRequest$outboundSchema` instead. */
    SubscriberListPushSubscriptionDeliveriesRequest$.outboundSchema = exports.SubscriberListPushSubscriptionDeliveriesRequest$outboundSchema;
})(SubscriberListPushSubscriptionDeliveriesRequest$ || (exports.SubscriberListPushSubscriptionDeliveriesRequest$ = SubscriberListPushSubscriptionDeliveriesRequest$ = {}));
function subscriberListPushSubscriptionDeliveriesRequestToJSON(subscriberListPushSubscriptionDeliveriesRequest) {
    return JSON.stringify(exports.SubscriberListPushSubscriptionDeliveriesRequest$outboundSchema.parse(subscriberListPushSubscriptionDeliveriesRequest));
}
function subscriberListPushSubscriptionDeliveriesRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.SubscriberListPushSubscriptionDeliveriesRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'SubscriberListPushSubscriptionDeliveriesRequest' from JSON`);
}
/** @internal */
exports.SubscriberListPushSubscriptionDeliveriesResponse$inboundSchema = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListPushSubscriptionDeliveriesResponse: components
        .ListPushSubscriptionDeliveriesResponse$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "HttpMeta": "httpMeta",
        "ListPushSubscriptionDeliveriesResponse": "listPushSubscriptionDeliveriesResponse",
        "Status": "status",
    });
});
/** @internal */
exports.SubscriberListPushSubscriptionDeliveriesResponse$outboundSchema = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    listPushSubscriptionDeliveriesResponse: components
        .ListPushSubscriptionDeliveriesResponse$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        httpMeta: "HttpMeta",
        listPushSubscriptionDeliveriesResponse: "ListPushSubscriptionDeliveriesResponse",
        status: "Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var SubscriberListPushSubscriptionDeliveriesResponse$;
(function (SubscriberListPushSubscriptionDeliveriesResponse$) {
    /** @deprecated use `SubscriberListPushSubscriptionDeliveriesResponse$inboundSchema` instead. */
    SubscriberListPushSubscriptionDeliveriesResponse$.inboundSchema = exports.SubscriberListPushSubscriptionDeliveriesResponse$inboundSchema;
    /** @deprecated use `SubscriberListPushSubscriptionDeliveriesResponse$outboundSchema` instead. */
    SubscriberListPushSubscriptionDeliveriesResponse$.outboundSchema = exports.SubscriberListPushSubscriptionDeliveriesResponse$outboundSchema;
})(SubscriberListPushSubscriptionDeliveriesResponse$ || (exports.SubscriberListPushSubscriptionDeliveriesResponse$ = SubscriberListPushSubscriptionDeliveriesResponse$ = {}));
function subscriberListPushSubscriptionDeliveriesResponseToJSON(subscriberListPushSubscriptionDeliveriesResponse) {
    return JSON.stringify(exports.SubscriberListPushSubscriptionDeliveriesResponse$outboundSchema.parse(subscriberListPushSubscriptionDeliveriesResponse));
}
function subscriberListPushSubscriptionDeliveriesResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.SubscriberListPushSubscriptionDeliveriesResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'SubscriberListPushSubscriptionDeliveriesResponse' from JSON`);
}
//# sourceMappingURL=subscriberlistpushsubscriptiondeliveries.js.map