/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { RetirementDistributionCreate$inboundSchema, RetirementDistributionCreate$outboundSchema, } from "./retirementdistributioncreate.js";
import { WithdrawalScheduleDetailsCreate$inboundSchema, WithdrawalScheduleDetailsCreate$outboundSchema, } from "./withdrawalscheduledetailscreate.js";
/** @internal */
export const AchWithdrawalScheduleCreate$inboundSchema = z.object({
    bank_relationship: z.string(),
    ira_distribution: RetirementDistributionCreate$inboundSchema.optional(),
    schedule_details: WithdrawalScheduleDetailsCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "bank_relationship": "bankRelationship",
        "ira_distribution": "iraDistribution",
        "schedule_details": "scheduleDetails",
    });
});
/** @internal */
export const AchWithdrawalScheduleCreate$outboundSchema = z.object({
    bankRelationship: z.string(),
    iraDistribution: RetirementDistributionCreate$outboundSchema.optional(),
    scheduleDetails: WithdrawalScheduleDetailsCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        bankRelationship: "bank_relationship",
        iraDistribution: "ira_distribution",
        scheduleDetails: "schedule_details",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var AchWithdrawalScheduleCreate$;
(function (AchWithdrawalScheduleCreate$) {
    /** @deprecated use `AchWithdrawalScheduleCreate$inboundSchema` instead. */
    AchWithdrawalScheduleCreate$.inboundSchema = AchWithdrawalScheduleCreate$inboundSchema;
    /** @deprecated use `AchWithdrawalScheduleCreate$outboundSchema` instead. */
    AchWithdrawalScheduleCreate$.outboundSchema = AchWithdrawalScheduleCreate$outboundSchema;
})(AchWithdrawalScheduleCreate$ || (AchWithdrawalScheduleCreate$ = {}));
export function achWithdrawalScheduleCreateToJSON(achWithdrawalScheduleCreate) {
    return JSON.stringify(AchWithdrawalScheduleCreate$outboundSchema.parse(achWithdrawalScheduleCreate));
}
export function achWithdrawalScheduleCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => AchWithdrawalScheduleCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AchWithdrawalScheduleCreate' from JSON`);
}
//# sourceMappingURL=achwithdrawalschedulecreate.js.map