/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BasketOrderCreate$inboundSchema, BasketOrderCreate$outboundSchema, } from "./basketordercreate.js";
/** @internal */
export const AddOrdersRequestCreate$inboundSchema = z.object({
    basket_orders: z.array(BasketOrderCreate$inboundSchema),
    name: z.string(),
}).transform((v) => {
    return remap$(v, {
        "basket_orders": "basketOrders",
    });
});
/** @internal */
export const AddOrdersRequestCreate$outboundSchema = z.object({
    basketOrders: z.array(BasketOrderCreate$outboundSchema),
    name: z.string(),
}).transform((v) => {
    return remap$(v, {
        basketOrders: "basket_orders",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var AddOrdersRequestCreate$;
(function (AddOrdersRequestCreate$) {
    /** @deprecated use `AddOrdersRequestCreate$inboundSchema` instead. */
    AddOrdersRequestCreate$.inboundSchema = AddOrdersRequestCreate$inboundSchema;
    /** @deprecated use `AddOrdersRequestCreate$outboundSchema` instead. */
    AddOrdersRequestCreate$.outboundSchema = AddOrdersRequestCreate$outboundSchema;
})(AddOrdersRequestCreate$ || (AddOrdersRequestCreate$ = {}));
export function addOrdersRequestCreateToJSON(addOrdersRequestCreate) {
    return JSON.stringify(AddOrdersRequestCreate$outboundSchema.parse(addOrdersRequestCreate));
}
export function addOrdersRequestCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => AddOrdersRequestCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AddOrdersRequestCreate' from JSON`);
}
//# sourceMappingURL=addordersrequestcreate.js.map