/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BeneficiaryCreate$inboundSchema, BeneficiaryCreate$outboundSchema, } from "./beneficiarycreate.js";
/** @internal */
export const BeneficiaryEnrollmentMetadataCreate$inboundSchema = z.object({
    contingent_beneficiaries: z.array(BeneficiaryCreate$inboundSchema).optional(),
    primary_beneficiaries: z.array(BeneficiaryCreate$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "contingent_beneficiaries": "contingentBeneficiaries",
        "primary_beneficiaries": "primaryBeneficiaries",
    });
});
/** @internal */
export const BeneficiaryEnrollmentMetadataCreate$outboundSchema = z.object({
    contingentBeneficiaries: z.array(BeneficiaryCreate$outboundSchema).optional(),
    primaryBeneficiaries: z.array(BeneficiaryCreate$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        contingentBeneficiaries: "contingent_beneficiaries",
        primaryBeneficiaries: "primary_beneficiaries",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BeneficiaryEnrollmentMetadataCreate$;
(function (BeneficiaryEnrollmentMetadataCreate$) {
    /** @deprecated use `BeneficiaryEnrollmentMetadataCreate$inboundSchema` instead. */
    BeneficiaryEnrollmentMetadataCreate$.inboundSchema = BeneficiaryEnrollmentMetadataCreate$inboundSchema;
    /** @deprecated use `BeneficiaryEnrollmentMetadataCreate$outboundSchema` instead. */
    BeneficiaryEnrollmentMetadataCreate$.outboundSchema = BeneficiaryEnrollmentMetadataCreate$outboundSchema;
})(BeneficiaryEnrollmentMetadataCreate$ || (BeneficiaryEnrollmentMetadataCreate$ = {}));
export function beneficiaryEnrollmentMetadataCreateToJSON(beneficiaryEnrollmentMetadataCreate) {
    return JSON.stringify(BeneficiaryEnrollmentMetadataCreate$outboundSchema.parse(beneficiaryEnrollmentMetadataCreate));
}
export function beneficiaryEnrollmentMetadataCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BeneficiaryEnrollmentMetadataCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BeneficiaryEnrollmentMetadataCreate' from JSON`);
}
//# sourceMappingURL=beneficiaryenrollmentmetadatacreate.js.map