/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const DecimalCreate$inboundSchema = z.object({
    value: z.string().optional(),
});
/** @internal */
export const DecimalCreate$outboundSchema = z.object({
    value: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var DecimalCreate$;
(function (DecimalCreate$) {
    /** @deprecated use `DecimalCreate$inboundSchema` instead. */
    DecimalCreate$.inboundSchema = DecimalCreate$inboundSchema;
    /** @deprecated use `DecimalCreate$outboundSchema` instead. */
    DecimalCreate$.outboundSchema = DecimalCreate$outboundSchema;
})(DecimalCreate$ || (DecimalCreate$ = {}));
export function decimalCreateToJSON(decimalCreate) {
    return JSON.stringify(DecimalCreate$outboundSchema.parse(decimalCreate));
}
export function decimalCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DecimalCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DecimalCreate' from JSON`);
}
//# sourceMappingURL=decimalcreate.js.map