/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { DecimalUpdate$inboundSchema, DecimalUpdate$outboundSchema, } from "./decimalupdate.js";
/** @internal */
export const DepositScheduleDetailsUpdate$inboundSchema = z.object({
    amount: DecimalUpdate$inboundSchema.optional(),
});
/** @internal */
export const DepositScheduleDetailsUpdate$outboundSchema = z.object({
    amount: DecimalUpdate$outboundSchema.optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var DepositScheduleDetailsUpdate$;
(function (DepositScheduleDetailsUpdate$) {
    /** @deprecated use `DepositScheduleDetailsUpdate$inboundSchema` instead. */
    DepositScheduleDetailsUpdate$.inboundSchema = DepositScheduleDetailsUpdate$inboundSchema;
    /** @deprecated use `DepositScheduleDetailsUpdate$outboundSchema` instead. */
    DepositScheduleDetailsUpdate$.outboundSchema = DepositScheduleDetailsUpdate$outboundSchema;
})(DepositScheduleDetailsUpdate$ || (DepositScheduleDetailsUpdate$ = {}));
export function depositScheduleDetailsUpdateToJSON(depositScheduleDetailsUpdate) {
    return JSON.stringify(DepositScheduleDetailsUpdate$outboundSchema.parse(depositScheduleDetailsUpdate));
}
export function depositScheduleDetailsUpdateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DepositScheduleDetailsUpdate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DepositScheduleDetailsUpdate' from JSON`);
}
//# sourceMappingURL=depositscheduledetailsupdate.js.map