/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const ForceApproveAchWithdrawalRequestCreate$inboundSchema = z.object({
    name: z.string(),
});
/** @internal */
export const ForceApproveAchWithdrawalRequestCreate$outboundSchema = z.object({
    name: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ForceApproveAchWithdrawalRequestCreate$;
(function (ForceApproveAchWithdrawalRequestCreate$) {
    /** @deprecated use `ForceApproveAchWithdrawalRequestCreate$inboundSchema` instead. */
    ForceApproveAchWithdrawalRequestCreate$.inboundSchema = ForceApproveAchWithdrawalRequestCreate$inboundSchema;
    /** @deprecated use `ForceApproveAchWithdrawalRequestCreate$outboundSchema` instead. */
    ForceApproveAchWithdrawalRequestCreate$.outboundSchema = ForceApproveAchWithdrawalRequestCreate$outboundSchema;
})(ForceApproveAchWithdrawalRequestCreate$ || (ForceApproveAchWithdrawalRequestCreate$ = {}));
export function forceApproveAchWithdrawalRequestCreateToJSON(forceApproveAchWithdrawalRequestCreate) {
    return JSON.stringify(ForceApproveAchWithdrawalRequestCreate$outboundSchema.parse(forceApproveAchWithdrawalRequestCreate));
}
export function forceApproveAchWithdrawalRequestCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ForceApproveAchWithdrawalRequestCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ForceApproveAchWithdrawalRequestCreate' from JSON`);
}
//# sourceMappingURL=forceapproveachwithdrawalrequestcreate.js.map