/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const ForceApproveWireWithdrawalRequestCreate$inboundSchema = z.object({
    name: z.string(),
});
/** @internal */
export const ForceApproveWireWithdrawalRequestCreate$outboundSchema = z.object({
    name: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ForceApproveWireWithdrawalRequestCreate$;
(function (ForceApproveWireWithdrawalRequestCreate$) {
    /** @deprecated use `ForceApproveWireWithdrawalRequestCreate$inboundSchema` instead. */
    ForceApproveWireWithdrawalRequestCreate$.inboundSchema = ForceApproveWireWithdrawalRequestCreate$inboundSchema;
    /** @deprecated use `ForceApproveWireWithdrawalRequestCreate$outboundSchema` instead. */
    ForceApproveWireWithdrawalRequestCreate$.outboundSchema = ForceApproveWireWithdrawalRequestCreate$outboundSchema;
})(ForceApproveWireWithdrawalRequestCreate$ || (ForceApproveWireWithdrawalRequestCreate$ = {}));
export function forceApproveWireWithdrawalRequestCreateToJSON(forceApproveWireWithdrawalRequestCreate) {
    return JSON.stringify(ForceApproveWireWithdrawalRequestCreate$outboundSchema.parse(forceApproveWireWithdrawalRequestCreate));
}
export function forceApproveWireWithdrawalRequestCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ForceApproveWireWithdrawalRequestCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ForceApproveWireWithdrawalRequestCreate' from JSON`);
}
//# sourceMappingURL=forceapprovewirewithdrawalrequestcreate.js.map