/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { catchUnrecognizedEnum, } from "../../types/enums.js";
import { ForeignNaturalPersonAccountEnrollmentMetadataCreate$inboundSchema, ForeignNaturalPersonAccountEnrollmentMetadataCreate$outboundSchema, } from "./foreignnaturalpersonaccountenrollmentmetadatacreate.js";
/**
 * Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
 */
export var ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan;
(function (ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan) {
    ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan["AutoEnrollDividendReinvestmentUnspecified"] = "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED";
    ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan["DividendReinvestmentEnroll"] = "DIVIDEND_REINVESTMENT_ENROLL";
    ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan["DividendReinvestmentDecline"] = "DIVIDEND_REINVESTMENT_DECLINE";
})(ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan || (ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan = {}));
/**
 * Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
 */
export var ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep;
(function (ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep) {
    ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep["AutoEnrollFdicCashSweepUnspecified"] = "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED";
    ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep["FdicCashSweepEnroll"] = "FDIC_CASH_SWEEP_ENROLL";
    ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep["FdicCashSweepDecline"] = "FDIC_CASH_SWEEP_DECLINE";
})(ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep || (ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep = {}));
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema = z
    .union([
    z.nativeEnum(ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema = z.union([
    z.nativeEnum(ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$;
(function (ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$) {
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$.inboundSchema = ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema;
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$.outboundSchema = ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema;
})(ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$ || (ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$ = {}));
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$inboundSchema = z
    .union([
    z.nativeEnum(ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$outboundSchema = z.union([
    z.nativeEnum(ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$;
(function (ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$) {
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$inboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$.inboundSchema = ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$inboundSchema;
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$outboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$.outboundSchema = ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$outboundSchema;
})(ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$ || (ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$ = {}));
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreate$inboundSchema = z.object({
    dividend_reinvestment_plan: ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema
        .optional(),
    fdic_cash_sweep: ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$inboundSchema
        .optional(),
    foreign_natural_person_account_enrollment_metadata: ForeignNaturalPersonAccountEnrollmentMetadataCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "dividend_reinvestment_plan": "dividendReinvestmentPlan",
        "fdic_cash_sweep": "fdicCashSweep",
        "foreign_natural_person_account_enrollment_metadata": "foreignNaturalPersonAccountEnrollmentMetadata",
    });
});
/** @internal */
export const ForeignJointAccountEnrollmentMetadataCreate$outboundSchema = z.object({
    dividendReinvestmentPlan: ForeignJointAccountEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema
        .optional(),
    fdicCashSweep: ForeignJointAccountEnrollmentMetadataCreateFdicCashSweep$outboundSchema
        .optional(),
    foreignNaturalPersonAccountEnrollmentMetadata: ForeignNaturalPersonAccountEnrollmentMetadataCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        dividendReinvestmentPlan: "dividend_reinvestment_plan",
        fdicCashSweep: "fdic_cash_sweep",
        foreignNaturalPersonAccountEnrollmentMetadata: "foreign_natural_person_account_enrollment_metadata",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ForeignJointAccountEnrollmentMetadataCreate$;
(function (ForeignJointAccountEnrollmentMetadataCreate$) {
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreate$inboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreate$.inboundSchema = ForeignJointAccountEnrollmentMetadataCreate$inboundSchema;
    /** @deprecated use `ForeignJointAccountEnrollmentMetadataCreate$outboundSchema` instead. */
    ForeignJointAccountEnrollmentMetadataCreate$.outboundSchema = ForeignJointAccountEnrollmentMetadataCreate$outboundSchema;
})(ForeignJointAccountEnrollmentMetadataCreate$ || (ForeignJointAccountEnrollmentMetadataCreate$ = {}));
export function foreignJointAccountEnrollmentMetadataCreateToJSON(foreignJointAccountEnrollmentMetadataCreate) {
    return JSON.stringify(ForeignJointAccountEnrollmentMetadataCreate$outboundSchema.parse(foreignJointAccountEnrollmentMetadataCreate));
}
export function foreignJointAccountEnrollmentMetadataCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ForeignJointAccountEnrollmentMetadataCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ForeignJointAccountEnrollmentMetadataCreate' from JSON`);
}
//# sourceMappingURL=foreignjointaccountenrollmentmetadatacreate.js.map