/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { catchUnrecognizedEnum, } from "../../types/enums.js";
/**
 * The type of identifier
 */
export var IdentifierUpdateType;
(function (IdentifierUpdateType) {
    IdentifierUpdateType["IdentifierTypeUnspecified"] = "IDENTIFIER_TYPE_UNSPECIFIED";
    IdentifierUpdateType["OriginatingAccountId"] = "ORIGINATING_ACCOUNT_ID";
    IdentifierUpdateType["OriginatingFdid"] = "ORIGINATING_FDID";
    IdentifierUpdateType["OriginatingCatReporterCrd"] = "ORIGINATING_CAT_REPORTER_CRD";
    IdentifierUpdateType["ClientAccountId"] = "CLIENT_ACCOUNT_ID";
})(IdentifierUpdateType || (IdentifierUpdateType = {}));
/** @internal */
export const IdentifierUpdateType$inboundSchema = z
    .union([
    z.nativeEnum(IdentifierUpdateType),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const IdentifierUpdateType$outboundSchema = z.union([
    z.nativeEnum(IdentifierUpdateType),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IdentifierUpdateType$;
(function (IdentifierUpdateType$) {
    /** @deprecated use `IdentifierUpdateType$inboundSchema` instead. */
    IdentifierUpdateType$.inboundSchema = IdentifierUpdateType$inboundSchema;
    /** @deprecated use `IdentifierUpdateType$outboundSchema` instead. */
    IdentifierUpdateType$.outboundSchema = IdentifierUpdateType$outboundSchema;
})(IdentifierUpdateType$ || (IdentifierUpdateType$ = {}));
/** @internal */
export const IdentifierUpdate$inboundSchema = z.object({
    type: IdentifierUpdateType$inboundSchema.optional(),
});
/** @internal */
export const IdentifierUpdate$outboundSchema = z.object({
    type: IdentifierUpdateType$outboundSchema.optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var IdentifierUpdate$;
(function (IdentifierUpdate$) {
    /** @deprecated use `IdentifierUpdate$inboundSchema` instead. */
    IdentifierUpdate$.inboundSchema = IdentifierUpdate$inboundSchema;
    /** @deprecated use `IdentifierUpdate$outboundSchema` instead. */
    IdentifierUpdate$.outboundSchema = IdentifierUpdate$outboundSchema;
})(IdentifierUpdate$ || (IdentifierUpdate$ = {}));
export function identifierUpdateToJSON(identifierUpdate) {
    return JSON.stringify(IdentifierUpdate$outboundSchema.parse(identifierUpdate));
}
export function identifierUpdateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => IdentifierUpdate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'IdentifierUpdate' from JSON`);
}
//# sourceMappingURL=identifierupdate.js.map