/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { catchUnrecognizedEnum, } from "../../types/enums.js";
/**
 * Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
 */
export var JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan;
(function (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan) {
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan["AutoEnrollDividendReinvestmentUnspecified"] = "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED";
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan["DividendReinvestmentEnroll"] = "DIVIDEND_REINVESTMENT_ENROLL";
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan["DividendReinvestmentDecline"] = "DIVIDEND_REINVESTMENT_DECLINE";
})(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan || (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan = {}));
/**
 * Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
 */
export var JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep;
(function (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep) {
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep["AutoEnrollFdicCashSweepUnspecified"] = "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED";
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep["FdicCashSweepEnroll"] = "FDIC_CASH_SWEEP_ENROLL";
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep["FdicCashSweepDecline"] = "FDIC_CASH_SWEEP_DECLINE";
})(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep || (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep = {}));
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema = z
    .union([
    z.nativeEnum(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema = z.union([
    z.nativeEnum(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$;
(function (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$) {
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$.inboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema;
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$.outboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema;
})(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$ || (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$ = {}));
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$inboundSchema = z
    .union([
    z.nativeEnum(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$outboundSchema = z.union([
    z.nativeEnum(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$;
(function (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$) {
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$inboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$.inboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$inboundSchema;
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$outboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$.outboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$outboundSchema;
})(JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$ || (JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$ = {}));
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$inboundSchema = z.object({
    dividend_reinvestment_plan: JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$inboundSchema
        .optional(),
    fdic_cash_sweep: JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$inboundSchema
        .optional(),
}).transform((v) => {
    return remap$(v, {
        "dividend_reinvestment_plan": "dividendReinvestmentPlan",
        "fdic_cash_sweep": "fdicCashSweep",
    });
});
/** @internal */
export const JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$outboundSchema = z.object({
    dividendReinvestmentPlan: JointWithRightsOfSurvivorshipEnrollmentMetadataCreateDividendReinvestmentPlan$outboundSchema
        .optional(),
    fdicCashSweep: JointWithRightsOfSurvivorshipEnrollmentMetadataCreateFdicCashSweep$outboundSchema
        .optional(),
}).transform((v) => {
    return remap$(v, {
        dividendReinvestmentPlan: "dividend_reinvestment_plan",
        fdicCashSweep: "fdic_cash_sweep",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$;
(function (JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$) {
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$inboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$.inboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$inboundSchema;
    /** @deprecated use `JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$outboundSchema` instead. */
    JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$.outboundSchema = JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$outboundSchema;
})(JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$ || (JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$ = {}));
export function jointWithRightsOfSurvivorshipEnrollmentMetadataCreateToJSON(jointWithRightsOfSurvivorshipEnrollmentMetadataCreate) {
    return JSON.stringify(JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$outboundSchema.parse(jointWithRightsOfSurvivorshipEnrollmentMetadataCreate));
}
export function jointWithRightsOfSurvivorshipEnrollmentMetadataCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => JointWithRightsOfSurvivorshipEnrollmentMetadataCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'JointWithRightsOfSurvivorshipEnrollmentMetadataCreate' from JSON`);
}
//# sourceMappingURL=jointwithrightsofsurvivorshipenrollmentmetadatacreate.js.map