/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { AvailableEnrollment$inboundSchema, AvailableEnrollment$outboundSchema, } from "./availableenrollment.js";
/** @internal */
export const ListAvailableEnrollmentsResponse$inboundSchema = z.object({
    available_enrollments: z.array(AvailableEnrollment$inboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        "available_enrollments": "availableEnrollments",
    });
});
/** @internal */
export const ListAvailableEnrollmentsResponse$outboundSchema = z.object({
    availableEnrollments: z.array(AvailableEnrollment$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        availableEnrollments: "available_enrollments",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ListAvailableEnrollmentsResponse$;
(function (ListAvailableEnrollmentsResponse$) {
    /** @deprecated use `ListAvailableEnrollmentsResponse$inboundSchema` instead. */
    ListAvailableEnrollmentsResponse$.inboundSchema = ListAvailableEnrollmentsResponse$inboundSchema;
    /** @deprecated use `ListAvailableEnrollmentsResponse$outboundSchema` instead. */
    ListAvailableEnrollmentsResponse$.outboundSchema = ListAvailableEnrollmentsResponse$outboundSchema;
})(ListAvailableEnrollmentsResponse$ || (ListAvailableEnrollmentsResponse$ = {}));
export function listAvailableEnrollmentsResponseToJSON(listAvailableEnrollmentsResponse) {
    return JSON.stringify(ListAvailableEnrollmentsResponse$outboundSchema.parse(listAvailableEnrollmentsResponse));
}
export function listAvailableEnrollmentsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAvailableEnrollmentsResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAvailableEnrollmentsResponse' from JSON`);
}
//# sourceMappingURL=listavailableenrollmentsresponse.js.map