/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Document$inboundSchema, Document$outboundSchema, } from "./document.js";
/** @internal */
export const ListDocumentsResponse$inboundSchema = z.object({
    document: z.array(Document$inboundSchema).optional(),
    next_page_token: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        "next_page_token": "nextPageToken",
    });
});
/** @internal */
export const ListDocumentsResponse$outboundSchema = z.object({
    document: z.array(Document$outboundSchema).optional(),
    nextPageToken: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        nextPageToken: "next_page_token",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ListDocumentsResponse$;
(function (ListDocumentsResponse$) {
    /** @deprecated use `ListDocumentsResponse$inboundSchema` instead. */
    ListDocumentsResponse$.inboundSchema = ListDocumentsResponse$inboundSchema;
    /** @deprecated use `ListDocumentsResponse$outboundSchema` instead. */
    ListDocumentsResponse$.outboundSchema = ListDocumentsResponse$outboundSchema;
})(ListDocumentsResponse$ || (ListDocumentsResponse$ = {}));
export function listDocumentsResponseToJSON(listDocumentsResponse) {
    return JSON.stringify(ListDocumentsResponse$outboundSchema.parse(listDocumentsResponse));
}
export function listDocumentsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListDocumentsResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListDocumentsResponse' from JSON`);
}
//# sourceMappingURL=listdocumentsresponse.js.map