/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { AchWithdrawalSchedule$inboundSchema, AchWithdrawalSchedule$outboundSchema, } from "./achwithdrawalschedule.js";
/** @internal */
export const ListAchWithdrawalSchedulesResponse$inboundSchema = z.object({
    ach_withdrawal_schedules: z.array(AchWithdrawalSchedule$inboundSchema)
        .optional(),
    next_page_token: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        "ach_withdrawal_schedules": "achWithdrawalSchedules",
        "next_page_token": "nextPageToken",
    });
});
/** @internal */
export const ListAchWithdrawalSchedulesResponse$outboundSchema = z.object({
    achWithdrawalSchedules: z.array(AchWithdrawalSchedule$outboundSchema)
        .optional(),
    nextPageToken: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        achWithdrawalSchedules: "ach_withdrawal_schedules",
        nextPageToken: "next_page_token",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ListAchWithdrawalSchedulesResponse$;
(function (ListAchWithdrawalSchedulesResponse$) {
    /** @deprecated use `ListAchWithdrawalSchedulesResponse$inboundSchema` instead. */
    ListAchWithdrawalSchedulesResponse$.inboundSchema = ListAchWithdrawalSchedulesResponse$inboundSchema;
    /** @deprecated use `ListAchWithdrawalSchedulesResponse$outboundSchema` instead. */
    ListAchWithdrawalSchedulesResponse$.outboundSchema = ListAchWithdrawalSchedulesResponse$outboundSchema;
})(ListAchWithdrawalSchedulesResponse$ || (ListAchWithdrawalSchedulesResponse$ = {}));
export function listAchWithdrawalSchedulesResponseToJSON(listAchWithdrawalSchedulesResponse) {
    return JSON.stringify(ListAchWithdrawalSchedulesResponse$outboundSchema.parse(listAchWithdrawalSchedulesResponse));
}
export function listAchWithdrawalSchedulesResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAchWithdrawalSchedulesResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAchWithdrawalSchedulesResponse' from JSON`);
}
//# sourceMappingURL=listachwithdrawalschedulesresponse.js.map