/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { CustomerReferralSourceCreate$inboundSchema, CustomerReferralSourceCreate$outboundSchema, } from "./customerreferralsourcecreate.js";
import { NegativeNewsCreate$inboundSchema, NegativeNewsCreate$outboundSchema, } from "./negativenewscreate.js";
import { OtherSourcesOfWealthCreate$inboundSchema, OtherSourcesOfWealthCreate$outboundSchema, } from "./othersourcesofwealthcreate.js";
/** @internal */
export const NaturalPersonFddCreate$inboundSchema = z.object({
    customer_non_referral_source: z.string().optional(),
    customer_referral_source: CustomerReferralSourceCreate$inboundSchema
        .optional(),
    employment_and_employer_description: z.string(),
    negative_news: NegativeNewsCreate$inboundSchema,
    other_sources_of_wealth: OtherSourcesOfWealthCreate$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "customer_non_referral_source": "customerNonReferralSource",
        "customer_referral_source": "customerReferralSource",
        "employment_and_employer_description": "employmentAndEmployerDescription",
        "negative_news": "negativeNews",
        "other_sources_of_wealth": "otherSourcesOfWealth",
    });
});
/** @internal */
export const NaturalPersonFddCreate$outboundSchema = z.object({
    customerNonReferralSource: z.string().optional(),
    customerReferralSource: CustomerReferralSourceCreate$outboundSchema
        .optional(),
    employmentAndEmployerDescription: z.string(),
    negativeNews: NegativeNewsCreate$outboundSchema,
    otherSourcesOfWealth: OtherSourcesOfWealthCreate$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        customerNonReferralSource: "customer_non_referral_source",
        customerReferralSource: "customer_referral_source",
        employmentAndEmployerDescription: "employment_and_employer_description",
        negativeNews: "negative_news",
        otherSourcesOfWealth: "other_sources_of_wealth",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var NaturalPersonFddCreate$;
(function (NaturalPersonFddCreate$) {
    /** @deprecated use `NaturalPersonFddCreate$inboundSchema` instead. */
    NaturalPersonFddCreate$.inboundSchema = NaturalPersonFddCreate$inboundSchema;
    /** @deprecated use `NaturalPersonFddCreate$outboundSchema` instead. */
    NaturalPersonFddCreate$.outboundSchema = NaturalPersonFddCreate$outboundSchema;
})(NaturalPersonFddCreate$ || (NaturalPersonFddCreate$ = {}));
export function naturalPersonFddCreateToJSON(naturalPersonFddCreate) {
    return JSON.stringify(NaturalPersonFddCreate$outboundSchema.parse(naturalPersonFddCreate));
}
export function naturalPersonFddCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => NaturalPersonFddCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'NaturalPersonFddCreate' from JSON`);
}
//# sourceMappingURL=naturalpersonfddcreate.js.map