/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alternativeAccountAccreditationGetAccountAccreditation } from "../funcs/alternativeAccountAccreditationGetAccountAccreditation.js";
import { alternativeAccountAccreditationSetAccountAccreditationType } from "../funcs/alternativeAccountAccreditationSetAccountAccreditationType.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AlternativeAccountAccreditation extends ClientSDK {
  /**
   * Get Account Accreditation
   *
   * @remarks
   * Gets the accreditation properties for the specified account.
   */
  async getAccountAccreditation(
    accountId: string,
    options?: RequestOptions,
  ): Promise<
    operations.AccountAccreditationServiceGetAccountAccreditationResponse
  > {
    return unwrapAsync(alternativeAccountAccreditationGetAccountAccreditation(
      this,
      accountId,
      options,
    ));
  }

  /**
   * Set Account Accreditation
   *
   * @remarks
   * Sets the accreditation type for an account. Accounts must be accredited to participate in alternative investment orders.
   */
  async setAccountAccreditationType(
    setAccountAccreditationTypeRequestCreate:
      components.SetAccountAccreditationTypeRequestCreate,
    accountId: string,
    options?: RequestOptions,
  ): Promise<
    operations.AccountAccreditationServiceSetAccountAccreditationTypeResponse
  > {
    return unwrapAsync(
      alternativeAccountAccreditationSetAccountAccreditationType(
        this,
        setAccountAccreditationTypeRequestCreate,
        accountId,
        options,
      ),
    );
  }
}
