/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { positionJournalsCancelPositionJournal } from "../funcs/positionJournalsCancelPositionJournal.js";
import { positionJournalsCreatePositionJournal } from "../funcs/positionJournalsCreatePositionJournal.js";
import { positionJournalsGetPositionJournal } from "../funcs/positionJournalsGetPositionJournal.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PositionJournals extends ClientSDK {
  /**
   * Create Position Journal
   *
   * @remarks
   * Creates a position journal
   */
  async createPositionJournal(
    request: components.PositionJournalCreate,
    options?: RequestOptions,
  ): Promise<operations.PositionJournalsCreatePositionJournalResponse> {
    return unwrapAsync(positionJournalsCreatePositionJournal(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Position Journal
   *
   * @remarks
   * Gets an existing position journal
   */
  async getPositionJournal(
    positionJournalId: string,
    options?: RequestOptions,
  ): Promise<operations.PositionJournalsGetPositionJournalResponse> {
    return unwrapAsync(positionJournalsGetPositionJournal(
      this,
      positionJournalId,
      options,
    ));
  }

  /**
   * Cancel Position Journal
   *
   * @remarks
   * Cancels an existing position journal
   */
  async cancelPositionJournal(
    cancelPositionJournalRequestCreate:
      components.CancelPositionJournalRequestCreate,
    positionJournalId: string,
    options?: RequestOptions,
  ): Promise<operations.PositionJournalsCancelPositionJournalResponse> {
    return unwrapAsync(positionJournalsCancelPositionJournal(
      this,
      cancelPositionJournalRequestCreate,
      positionJournalId,
      options,
    ));
  }
}
