/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AlternativeOrdersCreateAlternativeOrderRequest = {
  /**
   * The account id.
   */
  accountId: string;
  alternativeOrderCreate: components.AlternativeOrderCreate;
};

export type AlternativeOrdersCreateAlternativeOrderResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  alternativeOrder?: components.AlternativeOrder | undefined;
  /**
   * INVALID_ARGUMENT: The request has an invalid argument.
   *
   * @remarks
   * FAILED_PRECONDITION: The requested resource is not in the expected state.
   */
  status?: components.Status | undefined;
};

/** @internal */
export const AlternativeOrdersCreateAlternativeOrderRequest$inboundSchema:
  z.ZodType<
    AlternativeOrdersCreateAlternativeOrderRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    account_id: z.string(),
    AlternativeOrderCreate: components.AlternativeOrderCreate$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "AlternativeOrderCreate": "alternativeOrderCreate",
    });
  });

/** @internal */
export type AlternativeOrdersCreateAlternativeOrderRequest$Outbound = {
  account_id: string;
  AlternativeOrderCreate: components.AlternativeOrderCreate$Outbound;
};

/** @internal */
export const AlternativeOrdersCreateAlternativeOrderRequest$outboundSchema:
  z.ZodType<
    AlternativeOrdersCreateAlternativeOrderRequest$Outbound,
    z.ZodTypeDef,
    AlternativeOrdersCreateAlternativeOrderRequest
  > = z.object({
    accountId: z.string(),
    alternativeOrderCreate: components.AlternativeOrderCreate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      accountId: "account_id",
      alternativeOrderCreate: "AlternativeOrderCreate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AlternativeOrdersCreateAlternativeOrderRequest$ {
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderRequest$inboundSchema` instead. */
  export const inboundSchema =
    AlternativeOrdersCreateAlternativeOrderRequest$inboundSchema;
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderRequest$outboundSchema` instead. */
  export const outboundSchema =
    AlternativeOrdersCreateAlternativeOrderRequest$outboundSchema;
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderRequest$Outbound` instead. */
  export type Outbound =
    AlternativeOrdersCreateAlternativeOrderRequest$Outbound;
}

export function alternativeOrdersCreateAlternativeOrderRequestToJSON(
  alternativeOrdersCreateAlternativeOrderRequest:
    AlternativeOrdersCreateAlternativeOrderRequest,
): string {
  return JSON.stringify(
    AlternativeOrdersCreateAlternativeOrderRequest$outboundSchema.parse(
      alternativeOrdersCreateAlternativeOrderRequest,
    ),
  );
}

export function alternativeOrdersCreateAlternativeOrderRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AlternativeOrdersCreateAlternativeOrderRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AlternativeOrdersCreateAlternativeOrderRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AlternativeOrdersCreateAlternativeOrderRequest' from JSON`,
  );
}

/** @internal */
export const AlternativeOrdersCreateAlternativeOrderResponse$inboundSchema:
  z.ZodType<
    AlternativeOrdersCreateAlternativeOrderResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AlternativeOrder: components.AlternativeOrder$inboundSchema.optional(),
    Status: components.Status$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AlternativeOrder": "alternativeOrder",
      "Status": "status",
    });
  });

/** @internal */
export type AlternativeOrdersCreateAlternativeOrderResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  AlternativeOrder?: components.AlternativeOrder$Outbound | undefined;
  Status?: components.Status$Outbound | undefined;
};

/** @internal */
export const AlternativeOrdersCreateAlternativeOrderResponse$outboundSchema:
  z.ZodType<
    AlternativeOrdersCreateAlternativeOrderResponse$Outbound,
    z.ZodTypeDef,
    AlternativeOrdersCreateAlternativeOrderResponse
  > = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    alternativeOrder: components.AlternativeOrder$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      httpMeta: "HttpMeta",
      alternativeOrder: "AlternativeOrder",
      status: "Status",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AlternativeOrdersCreateAlternativeOrderResponse$ {
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderResponse$inboundSchema` instead. */
  export const inboundSchema =
    AlternativeOrdersCreateAlternativeOrderResponse$inboundSchema;
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderResponse$outboundSchema` instead. */
  export const outboundSchema =
    AlternativeOrdersCreateAlternativeOrderResponse$outboundSchema;
  /** @deprecated use `AlternativeOrdersCreateAlternativeOrderResponse$Outbound` instead. */
  export type Outbound =
    AlternativeOrdersCreateAlternativeOrderResponse$Outbound;
}

export function alternativeOrdersCreateAlternativeOrderResponseToJSON(
  alternativeOrdersCreateAlternativeOrderResponse:
    AlternativeOrdersCreateAlternativeOrderResponse,
): string {
  return JSON.stringify(
    AlternativeOrdersCreateAlternativeOrderResponse$outboundSchema.parse(
      alternativeOrdersCreateAlternativeOrderResponse,
    ),
  );
}

export function alternativeOrdersCreateAlternativeOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AlternativeOrdersCreateAlternativeOrderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AlternativeOrdersCreateAlternativeOrderResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AlternativeOrdersCreateAlternativeOrderResponse' from JSON`,
  );
}
