/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CashJournalSchedulesCancelCashJournalScheduleRequest = {
  /**
   * The cashJournalSchedule id.
   */
  cashJournalScheduleId: string;
  cancelCashJournalScheduleRequestCreate:
    components.CancelCashJournalScheduleRequestCreate;
};

export type CashJournalSchedulesCancelCashJournalScheduleResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  cashJournalSchedule?: components.CashJournalSchedule | undefined;
  /**
   * INVALID_ARGUMENT: The request has an invalid argument.
   *
   * @remarks
   * FAILED_PRECONDITION: The schedule is in a state that doesn't allow cancellation.
   */
  status?: components.Status | undefined;
};

/** @internal */
export const CashJournalSchedulesCancelCashJournalScheduleRequest$inboundSchema:
  z.ZodType<
    CashJournalSchedulesCancelCashJournalScheduleRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    cashJournalSchedule_id: z.string(),
    CancelCashJournalScheduleRequestCreate:
      components.CancelCashJournalScheduleRequestCreate$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "cashJournalSchedule_id": "cashJournalScheduleId",
      "CancelCashJournalScheduleRequestCreate":
        "cancelCashJournalScheduleRequestCreate",
    });
  });

/** @internal */
export type CashJournalSchedulesCancelCashJournalScheduleRequest$Outbound = {
  cashJournalSchedule_id: string;
  CancelCashJournalScheduleRequestCreate:
    components.CancelCashJournalScheduleRequestCreate$Outbound;
};

/** @internal */
export const CashJournalSchedulesCancelCashJournalScheduleRequest$outboundSchema:
  z.ZodType<
    CashJournalSchedulesCancelCashJournalScheduleRequest$Outbound,
    z.ZodTypeDef,
    CashJournalSchedulesCancelCashJournalScheduleRequest
  > = z.object({
    cashJournalScheduleId: z.string(),
    cancelCashJournalScheduleRequestCreate:
      components.CancelCashJournalScheduleRequestCreate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      cashJournalScheduleId: "cashJournalSchedule_id",
      cancelCashJournalScheduleRequestCreate:
        "CancelCashJournalScheduleRequestCreate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CashJournalSchedulesCancelCashJournalScheduleRequest$ {
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleRequest$inboundSchema` instead. */
  export const inboundSchema =
    CashJournalSchedulesCancelCashJournalScheduleRequest$inboundSchema;
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleRequest$outboundSchema` instead. */
  export const outboundSchema =
    CashJournalSchedulesCancelCashJournalScheduleRequest$outboundSchema;
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleRequest$Outbound` instead. */
  export type Outbound =
    CashJournalSchedulesCancelCashJournalScheduleRequest$Outbound;
}

export function cashJournalSchedulesCancelCashJournalScheduleRequestToJSON(
  cashJournalSchedulesCancelCashJournalScheduleRequest:
    CashJournalSchedulesCancelCashJournalScheduleRequest,
): string {
  return JSON.stringify(
    CashJournalSchedulesCancelCashJournalScheduleRequest$outboundSchema.parse(
      cashJournalSchedulesCancelCashJournalScheduleRequest,
    ),
  );
}

export function cashJournalSchedulesCancelCashJournalScheduleRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CashJournalSchedulesCancelCashJournalScheduleRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CashJournalSchedulesCancelCashJournalScheduleRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CashJournalSchedulesCancelCashJournalScheduleRequest' from JSON`,
  );
}

/** @internal */
export const CashJournalSchedulesCancelCashJournalScheduleResponse$inboundSchema:
  z.ZodType<
    CashJournalSchedulesCancelCashJournalScheduleResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    CashJournalSchedule: components.CashJournalSchedule$inboundSchema
      .optional(),
    Status: components.Status$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "CashJournalSchedule": "cashJournalSchedule",
      "Status": "status",
    });
  });

/** @internal */
export type CashJournalSchedulesCancelCashJournalScheduleResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  CashJournalSchedule?: components.CashJournalSchedule$Outbound | undefined;
  Status?: components.Status$Outbound | undefined;
};

/** @internal */
export const CashJournalSchedulesCancelCashJournalScheduleResponse$outboundSchema:
  z.ZodType<
    CashJournalSchedulesCancelCashJournalScheduleResponse$Outbound,
    z.ZodTypeDef,
    CashJournalSchedulesCancelCashJournalScheduleResponse
  > = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    cashJournalSchedule: components.CashJournalSchedule$outboundSchema
      .optional(),
    status: components.Status$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      httpMeta: "HttpMeta",
      cashJournalSchedule: "CashJournalSchedule",
      status: "Status",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CashJournalSchedulesCancelCashJournalScheduleResponse$ {
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleResponse$inboundSchema` instead. */
  export const inboundSchema =
    CashJournalSchedulesCancelCashJournalScheduleResponse$inboundSchema;
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleResponse$outboundSchema` instead. */
  export const outboundSchema =
    CashJournalSchedulesCancelCashJournalScheduleResponse$outboundSchema;
  /** @deprecated use `CashJournalSchedulesCancelCashJournalScheduleResponse$Outbound` instead. */
  export type Outbound =
    CashJournalSchedulesCancelCashJournalScheduleResponse$Outbound;
}

export function cashJournalSchedulesCancelCashJournalScheduleResponseToJSON(
  cashJournalSchedulesCancelCashJournalScheduleResponse:
    CashJournalSchedulesCancelCashJournalScheduleResponse,
): string {
  return JSON.stringify(
    CashJournalSchedulesCancelCashJournalScheduleResponse$outboundSchema.parse(
      cashJournalSchedulesCancelCashJournalScheduleResponse,
    ),
  );
}

export function cashJournalSchedulesCancelCashJournalScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CashJournalSchedulesCancelCashJournalScheduleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CashJournalSchedulesCancelCashJournalScheduleResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CashJournalSchedulesCancelCashJournalScheduleResponse' from JSON`,
  );
}
