/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PreIpoCompaniesListPreIpoCompaniesRequest = {
  /**
   * The maximum number of Pre IPO Companies to return. The service may return fewer than this value. If unspecified, at most 100 Pre IPO Companies will be returned. The maximum value is 100; values above 100 will be coerced to 100.
   */
  pageSize?: number | undefined;
  /**
   * A page token, received from a previous `ListPreIpoCompaniesRequest` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPreIpoCompaniesRequest` must match the call that provided the page token.
   */
  pageToken?: string | undefined;
};

export type PreIpoCompaniesListPreIpoCompaniesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  listPreIpoCompaniesResponse?:
    | components.ListPreIpoCompaniesResponse
    | undefined;
  /**
   * INVALID_ARGUMENT: The request has an invalid argument.
   */
  status?: components.Status | undefined;
};

/** @internal */
export const PreIpoCompaniesListPreIpoCompaniesRequest$inboundSchema: z.ZodType<
  PreIpoCompaniesListPreIpoCompaniesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_size: z.number().int().optional(),
  page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "page_token": "pageToken",
  });
});

/** @internal */
export type PreIpoCompaniesListPreIpoCompaniesRequest$Outbound = {
  page_size?: number | undefined;
  page_token?: string | undefined;
};

/** @internal */
export const PreIpoCompaniesListPreIpoCompaniesRequest$outboundSchema:
  z.ZodType<
    PreIpoCompaniesListPreIpoCompaniesRequest$Outbound,
    z.ZodTypeDef,
    PreIpoCompaniesListPreIpoCompaniesRequest
  > = z.object({
    pageSize: z.number().int().optional(),
    pageToken: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
      pageToken: "page_token",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreIpoCompaniesListPreIpoCompaniesRequest$ {
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesRequest$inboundSchema` instead. */
  export const inboundSchema =
    PreIpoCompaniesListPreIpoCompaniesRequest$inboundSchema;
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesRequest$outboundSchema` instead. */
  export const outboundSchema =
    PreIpoCompaniesListPreIpoCompaniesRequest$outboundSchema;
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesRequest$Outbound` instead. */
  export type Outbound = PreIpoCompaniesListPreIpoCompaniesRequest$Outbound;
}

export function preIpoCompaniesListPreIpoCompaniesRequestToJSON(
  preIpoCompaniesListPreIpoCompaniesRequest:
    PreIpoCompaniesListPreIpoCompaniesRequest,
): string {
  return JSON.stringify(
    PreIpoCompaniesListPreIpoCompaniesRequest$outboundSchema.parse(
      preIpoCompaniesListPreIpoCompaniesRequest,
    ),
  );
}

export function preIpoCompaniesListPreIpoCompaniesRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PreIpoCompaniesListPreIpoCompaniesRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreIpoCompaniesListPreIpoCompaniesRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PreIpoCompaniesListPreIpoCompaniesRequest' from JSON`,
  );
}

/** @internal */
export const PreIpoCompaniesListPreIpoCompaniesResponse$inboundSchema:
  z.ZodType<PreIpoCompaniesListPreIpoCompaniesResponse, z.ZodTypeDef, unknown> =
    z.object({
      HttpMeta: components.HTTPMetadata$inboundSchema,
      ListPreIpoCompaniesResponse: components
        .ListPreIpoCompaniesResponse$inboundSchema.optional(),
      Status: components.Status$inboundSchema.optional(),
    }).transform((v) => {
      return remap$(v, {
        "HttpMeta": "httpMeta",
        "ListPreIpoCompaniesResponse": "listPreIpoCompaniesResponse",
        "Status": "status",
      });
    });

/** @internal */
export type PreIpoCompaniesListPreIpoCompaniesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  ListPreIpoCompaniesResponse?:
    | components.ListPreIpoCompaniesResponse$Outbound
    | undefined;
  Status?: components.Status$Outbound | undefined;
};

/** @internal */
export const PreIpoCompaniesListPreIpoCompaniesResponse$outboundSchema:
  z.ZodType<
    PreIpoCompaniesListPreIpoCompaniesResponse$Outbound,
    z.ZodTypeDef,
    PreIpoCompaniesListPreIpoCompaniesResponse
  > = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    listPreIpoCompaniesResponse: components
      .ListPreIpoCompaniesResponse$outboundSchema.optional(),
    status: components.Status$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      httpMeta: "HttpMeta",
      listPreIpoCompaniesResponse: "ListPreIpoCompaniesResponse",
      status: "Status",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreIpoCompaniesListPreIpoCompaniesResponse$ {
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesResponse$inboundSchema` instead. */
  export const inboundSchema =
    PreIpoCompaniesListPreIpoCompaniesResponse$inboundSchema;
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesResponse$outboundSchema` instead. */
  export const outboundSchema =
    PreIpoCompaniesListPreIpoCompaniesResponse$outboundSchema;
  /** @deprecated use `PreIpoCompaniesListPreIpoCompaniesResponse$Outbound` instead. */
  export type Outbound = PreIpoCompaniesListPreIpoCompaniesResponse$Outbound;
}

export function preIpoCompaniesListPreIpoCompaniesResponseToJSON(
  preIpoCompaniesListPreIpoCompaniesResponse:
    PreIpoCompaniesListPreIpoCompaniesResponse,
): string {
  return JSON.stringify(
    PreIpoCompaniesListPreIpoCompaniesResponse$outboundSchema.parse(
      preIpoCompaniesListPreIpoCompaniesResponse,
    ),
  );
}

export function preIpoCompaniesListPreIpoCompaniesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PreIpoCompaniesListPreIpoCompaniesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreIpoCompaniesListPreIpoCompaniesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PreIpoCompaniesListPreIpoCompaniesResponse' from JSON`,
  );
}
