/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountTransfersAcceptTransfer } from "../funcs/accountTransfersAcceptTransfer.js";
import { accountTransfersCreateTransfer } from "../funcs/accountTransfersCreateTransfer.js";
import { accountTransfersGetTransfer } from "../funcs/accountTransfersGetTransfer.js";
import { accountTransfersListTransfers } from "../funcs/accountTransfersListTransfers.js";
import { accountTransfersRejectTransfer } from "../funcs/accountTransfersRejectTransfer.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import { unwrapResultIterator } from "../types/operations.js";
export class AccountTransfers extends ClientSDK {
    /**
     * Create Transfer
     *
     * @remarks
     * Creates a transfer
     */
    async createTransfer(transferCreate, correspondentId, accountId, requestId, options) {
        return unwrapAsync(accountTransfersCreateTransfer(this, transferCreate, correspondentId, accountId, requestId, options));
    }
    /**
     * List Transfers
     *
     * @remarks
     * Lists existing transfers using a CEL filter.
     */
    async listTransfers(request, options) {
        return unwrapResultIterator(accountTransfersListTransfers(this, request, options));
    }
    /**
     * Accept Transfer
     *
     * @remarks
     * Accept one side (incoming/outgoing) of an internal Ascend transfer. When both the incoming side and outgoing side of the transfer have been accepted then bookkeeping is done immediately. If neither, or only one side of a transfer is accepted, then both sides of the internal perform bookkeeping one full settlement day after they went into the bookkeeping queue.
     */
    async acceptTransfer(acceptTransferRequestCreate, correspondentId, accountId, transferId, options) {
        return unwrapAsync(accountTransfersAcceptTransfer(this, acceptTransferRequestCreate, correspondentId, accountId, transferId, options));
    }
    /**
     * Reject Transfer
     *
     * @remarks
     * Reject one side (incoming/outgoing) of an internal Ascend transfer. Rejecting one side automatically moves the contra side of the transfer to be rejected as well.
     */
    async rejectTransfer(rejectTransferRequestCreate, correspondentId, accountId, transferId, options) {
        return unwrapAsync(accountTransfersRejectTransfer(this, rejectTransferRequestCreate, correspondentId, accountId, transferId, options));
    }
    /**
     * Get Transfer
     *
     * @remarks
     * Gets an existing transfer
     */
    async getTransfer(correspondentId, accountId, transferId, options) {
        return unwrapAsync(accountTransfersGetTransfer(this, correspondentId, accountId, transferId, options));
    }
}
//# sourceMappingURL=accounttransfers.js.map