/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountCreationCreateAccount } from "../funcs/accountCreationCreateAccount.js";
import { accountCreationGetAccount } from "../funcs/accountCreationGetAccount.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class AccountCreation extends ClientSDK {
    /**
     * Create Account
     *
     * @remarks
     * CREATE Creates an account.
     */
    async createAccount(request, options) {
        return unwrapAsync(accountCreationCreateAccount(this, request, options));
    }
    /**
     * Get Account
     *
     * @remarks
     * READ Get Account
     */
    async getAccount(accountId, view, options) {
        return unwrapAsync(accountCreationGetAccount(this, accountId, view, options));
    }
}
//# sourceMappingURL=accountcreation.js.map