/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { instantCashTransferICTCancelICTDeposit } from "../funcs/instantCashTransferICTCancelICTDeposit.js";
import { instantCashTransferICTCancelICTWithdrawal } from "../funcs/instantCashTransferICTCancelICTWithdrawal.js";
import { instantCashTransferICTCreateICTDeposit } from "../funcs/instantCashTransferICTCreateICTDeposit.js";
import { instantCashTransferICTCreateICTWithdrawal } from "../funcs/instantCashTransferICTCreateICTWithdrawal.js";
import { instantCashTransferICTGetICTDeposit } from "../funcs/instantCashTransferICTGetICTDeposit.js";
import { instantCashTransferICTGetICTWithdrawal } from "../funcs/instantCashTransferICTGetICTWithdrawal.js";
import { instantCashTransferICTLocateICTReport } from "../funcs/instantCashTransferICTLocateICTReport.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class InstantCashTransferICT extends ClientSDK {
    /**
     * Create ICT Deposit
     *
     * @remarks
     * Creates an ICT deposit
     */
    async createIctDeposit(ictDepositCreate, accountId, options) {
        return unwrapAsync(instantCashTransferICTCreateICTDeposit(this, ictDepositCreate, accountId, options));
    }
    /**
     * Get ICT Deposit
     *
     * @remarks
     * Gets an existing ICT deposit
     */
    async getIctDeposit(accountId, ictDepositId, options) {
        return unwrapAsync(instantCashTransferICTGetICTDeposit(this, accountId, ictDepositId, options));
    }
    /**
     * Cancel ICT Deposit
     *
     * @remarks
     * Cancels an existing ICT deposit
     */
    async cancelIctDeposit(cancelIctDepositRequestCreate, accountId, ictDepositId, options) {
        return unwrapAsync(instantCashTransferICTCancelICTDeposit(this, cancelIctDepositRequestCreate, accountId, ictDepositId, options));
    }
    /**
     * Create ICT Withdrawal
     *
     * @remarks
     * Creates an ICT withdrawal
     */
    async createIctWithdrawal(ictWithdrawalCreate, accountId, options) {
        return unwrapAsync(instantCashTransferICTCreateICTWithdrawal(this, ictWithdrawalCreate, accountId, options));
    }
    /**
     * Get ICT Withdrawal
     *
     * @remarks
     * Gets an existing ICT withdrawal
     */
    async getIctWithdrawal(accountId, ictWithdrawalId, options) {
        return unwrapAsync(instantCashTransferICTGetICTWithdrawal(this, accountId, ictWithdrawalId, options));
    }
    /**
     * Cancel ICT Withdrawal
     *
     * @remarks
     * Cancels an existing ICT withdrawal
     */
    async cancelIctWithdrawal(cancelIctWithdrawalRequestCreate, accountId, ictWithdrawalId, options) {
        return unwrapAsync(instantCashTransferICTCancelICTWithdrawal(this, cancelIctWithdrawalRequestCreate, accountId, ictWithdrawalId, options));
    }
    /**
     * Locate ICT Report
     *
     * @remarks
     * Returns a signed link pointing to a recon report file for a specific ICT batch.
     */
    async locateIctReport(request, options) {
        return unwrapAsync(instantCashTransferICTLocateICTReport(this, request, options));
    }
}
//# sourceMappingURL=instantcashtransferict.js.map