/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to accept internal Ascend transfers.
 */
export type AcceptTransferRequestCreate = {
  /**
   * Comment to add to the transfer record's audit trail.
   */
  comment?: string | undefined;
  /**
   * The name of the transfer to accept. Format: correspondents/{correspondent_id}/accounts/{account_id}/transfers/{transfer_id}
   */
  name: string;
};

/** @internal */
export const AcceptTransferRequestCreate$inboundSchema: z.ZodType<
  AcceptTransferRequestCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  name: z.string(),
});

/** @internal */
export type AcceptTransferRequestCreate$Outbound = {
  comment?: string | undefined;
  name: string;
};

/** @internal */
export const AcceptTransferRequestCreate$outboundSchema: z.ZodType<
  AcceptTransferRequestCreate$Outbound,
  z.ZodTypeDef,
  AcceptTransferRequestCreate
> = z.object({
  comment: z.string().optional(),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AcceptTransferRequestCreate$ {
  /** @deprecated use `AcceptTransferRequestCreate$inboundSchema` instead. */
  export const inboundSchema = AcceptTransferRequestCreate$inboundSchema;
  /** @deprecated use `AcceptTransferRequestCreate$outboundSchema` instead. */
  export const outboundSchema = AcceptTransferRequestCreate$outboundSchema;
  /** @deprecated use `AcceptTransferRequestCreate$Outbound` instead. */
  export type Outbound = AcceptTransferRequestCreate$Outbound;
}
