/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CheckWithdrawalSchedule,
  CheckWithdrawalSchedule$inboundSchema,
  CheckWithdrawalSchedule$Outbound,
  CheckWithdrawalSchedule$outboundSchema,
} from "./checkwithdrawalschedule.js";

/**
 * A paged response containing a list of Check withdrawal transfer schedules
 */
export type ListCheckWithdrawalSchedulesResponse = {
  /**
   * The list of transfer schedules
   */
  checkWithdrawalSchedules?: Array<CheckWithdrawalSchedule> | undefined;
  /**
   * The next page token
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const ListCheckWithdrawalSchedulesResponse$inboundSchema: z.ZodType<
  ListCheckWithdrawalSchedulesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  check_withdrawal_schedules: z.array(CheckWithdrawalSchedule$inboundSchema)
    .optional(),
  next_page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "check_withdrawal_schedules": "checkWithdrawalSchedules",
    "next_page_token": "nextPageToken",
  });
});

/** @internal */
export type ListCheckWithdrawalSchedulesResponse$Outbound = {
  check_withdrawal_schedules?:
    | Array<CheckWithdrawalSchedule$Outbound>
    | undefined;
  next_page_token?: string | undefined;
};

/** @internal */
export const ListCheckWithdrawalSchedulesResponse$outboundSchema: z.ZodType<
  ListCheckWithdrawalSchedulesResponse$Outbound,
  z.ZodTypeDef,
  ListCheckWithdrawalSchedulesResponse
> = z.object({
  checkWithdrawalSchedules: z.array(CheckWithdrawalSchedule$outboundSchema)
    .optional(),
  nextPageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    checkWithdrawalSchedules: "check_withdrawal_schedules",
    nextPageToken: "next_page_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCheckWithdrawalSchedulesResponse$ {
  /** @deprecated use `ListCheckWithdrawalSchedulesResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListCheckWithdrawalSchedulesResponse$inboundSchema;
  /** @deprecated use `ListCheckWithdrawalSchedulesResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListCheckWithdrawalSchedulesResponse$outboundSchema;
  /** @deprecated use `ListCheckWithdrawalSchedulesResponse$Outbound` instead. */
  export type Outbound = ListCheckWithdrawalSchedulesResponse$Outbound;
}

export function listCheckWithdrawalSchedulesResponseToJSON(
  listCheckWithdrawalSchedulesResponse: ListCheckWithdrawalSchedulesResponse,
): string {
  return JSON.stringify(
    ListCheckWithdrawalSchedulesResponse$outboundSchema.parse(
      listCheckWithdrawalSchedulesResponse,
    ),
  );
}

export function listCheckWithdrawalSchedulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCheckWithdrawalSchedulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListCheckWithdrawalSchedulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCheckWithdrawalSchedulesResponse' from JSON`,
  );
}
