/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request message for SetOptionExtraReportingData.
 */
export type SetOptionExtraReportingDataRequestCreate = {
  /**
   * The time the correspondent confirmed receipt of the cancellation.
   */
  cancelConfirmedTime: Date | null;
  /**
   * Format: accounts/{account_id}/optionOrders/{option_order_id}
   */
  name: string;
};

/** @internal */
export const SetOptionExtraReportingDataRequestCreate$inboundSchema: z.ZodType<
  SetOptionExtraReportingDataRequestCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  cancel_confirmed_time: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    "cancel_confirmed_time": "cancelConfirmedTime",
  });
});

/** @internal */
export type SetOptionExtraReportingDataRequestCreate$Outbound = {
  cancel_confirmed_time: string | null;
  name: string;
};

/** @internal */
export const SetOptionExtraReportingDataRequestCreate$outboundSchema: z.ZodType<
  SetOptionExtraReportingDataRequestCreate$Outbound,
  z.ZodTypeDef,
  SetOptionExtraReportingDataRequestCreate
> = z.object({
  cancelConfirmedTime: z.nullable(z.date().transform(v => v.toISOString())),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    cancelConfirmedTime: "cancel_confirmed_time",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetOptionExtraReportingDataRequestCreate$ {
  /** @deprecated use `SetOptionExtraReportingDataRequestCreate$inboundSchema` instead. */
  export const inboundSchema =
    SetOptionExtraReportingDataRequestCreate$inboundSchema;
  /** @deprecated use `SetOptionExtraReportingDataRequestCreate$outboundSchema` instead. */
  export const outboundSchema =
    SetOptionExtraReportingDataRequestCreate$outboundSchema;
  /** @deprecated use `SetOptionExtraReportingDataRequestCreate$Outbound` instead. */
  export type Outbound = SetOptionExtraReportingDataRequestCreate$Outbound;
}

export function setOptionExtraReportingDataRequestCreateToJSON(
  setOptionExtraReportingDataRequestCreate:
    SetOptionExtraReportingDataRequestCreate,
): string {
  return JSON.stringify(
    SetOptionExtraReportingDataRequestCreate$outboundSchema.parse(
      setOptionExtraReportingDataRequestCreate,
    ),
  );
}

export function setOptionExtraReportingDataRequestCreateFromJSON(
  jsonString: string,
): SafeParseResult<
  SetOptionExtraReportingDataRequestCreate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SetOptionExtraReportingDataRequestCreate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SetOptionExtraReportingDataRequestCreate' from JSON`,
  );
}
