"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const vitest_1 = require("vitest");
const index_js_1 = require("../index.js");
const testclient_js_1 = require("./testclient.js");
(0, vitest_1.test)("Checks Check Deposits Get Check Deposit", async () => {
    const testHttpClient = (0, testclient_js_1.createTestHTTPClient)("CheckDeposits_GetCheckDeposit");
    const apexascend = new index_js_1.Apexascend({
        serverURL: process.env["SERVICE_ACCOUNT_CREDS_URL"] ?? "",
        security: {
            apiKey: process.env["API_KEY"] ?? "value",
            serviceAccountCreds: {
                privateKey: process.env["SERVICE_ACCOUNT_CREDS_PRIVATE_KEY"] ?? "value",
                name: process.env["SERVICE_ACCOUNT_CREDS_NAME"] ?? "value",
                organization: process.env["SERVICE_ACCOUNT_CREDS_ORGANIZATION"]
                    ?? "value",
                type: process.env["SERVICE_ACCOUNT_CREDS_TYPE"] ?? "value",
            },
        },
        httpClient: testHttpClient,
    });
    const result = await apexascend.checks.getCheckDeposit("01JHGTEPC6ZTAHCFRH2MD3VJJT", "20250811022796");
    (0, vitest_1.expect)(result.httpMeta.response.status).toBe(200);
});
//# sourceMappingURL=checks.test.js.map